from datetime import datetime
from uuid import UUID
from pydantic import BaseModel
from app.core.plan_config import PlanTier, SubscriptionStatus

class PlanLimitsResponse(BaseModel):
    max_ai_responses_per_month: int
    max_knowledge_bases: int
    max_documents_per_kb: int
    max_members: int
    max_storage_bytes: int
    allows_api_keys: bool
    allows_webhooks: bool
    allows_custom_branding: bool

class SubscriptionResponse(BaseModel):
    id: UUID
    organization_id: UUID
    plan_tier: PlanTier
    status: SubscriptionStatus
    current_period_start: datetime
    current_period_end: datetime
    limits: PlanLimitsResponse
    # Stripe state, not ids: the dashboard needs to know whether a plan change
    # should open checkout (no subscription yet) or the billing portal (Stripe
    # already bills this org, so it owns the swap, proration and cancellation).
    has_billing_account: bool
    has_stripe_subscription: bool

class CheckoutRequest(BaseModel): #over here the urls are provied by out frontend
    price_id: str
    success_url: str #where to direct if payment is succesfull
    cancel_url: str

class PortalRequest(BaseModel):
    return_url: str # where to redirected after ther're done in the portal

class CheckoutResponse(BaseModel): #the url is generated by stripe
    checkout_url: str # stripe hosted - url frontend redirects user here
