"""added messagefeedback table

Revision ID: 078e968c39a5
Revises: e82568ada365
Create Date: 2026-07-13 12:02:57.857497

"""
from typing import Sequence, Union
from pgvector.sqlalchemy import Vector

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '078e968c39a5'
down_revision: Union[str, Sequence[str], None] = 'e82568ada365'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_feedbacks',
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('feedback', sa.Enum('POSITIVE', 'NEGATIVE', name='feedbacktype'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_feedbacks_message_id'), 'message_feedbacks', ['message_id'], unique=False)
    op.alter_column('document_chunks', 'embedding',existing_type=Vector(1536),nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_chunks', 'embedding',existing_type=Vector(1536),nullable=True)
    op.drop_index(op.f('ix_message_feedbacks_message_id'), table_name='message_feedbacks')
    op.drop_table('message_feedbacks')
    # ### end Alembic commands ###
