"""fix_webhook_response_body_nullable

Revision ID: 31002f9008d3
Revises: f62ffc844cbb
Create Date: 2026-08-10 22:58:36.961608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31002f9008d3'
down_revision: Union[str, Sequence[str], None] = 'f62ffc844cbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('webhook_deliveries', 'response_body',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('webhook_deliveries', 'response_body',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
