"""add ticket assignment

Revision ID: 45c4ab7611a9
Revises: 7f041754f818
Create Date: 2026-07-15 14:22:09.164266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45c4ab7611a9'
down_revision: Union[str, Sequence[str], None] = '7f041754f818'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('assigned_to_user_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_tickets_assigned_to_user_id'), 'tickets', ['assigned_to_user_id'], unique=False)
    op.create_foreign_key(None, 'tickets', 'users', ['assigned_to_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_index(op.f('ix_tickets_assigned_to_user_id'), table_name='tickets')
    op.drop_column('tickets', 'assigned_to_user_id')
    # ### end Alembic commands ###
