"""add_composite_indexes

Revision ID: 47c017d02682
Revises: 05cd2f2d7144
Create Date: 2026-08-01 17:08:44.891914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47c017d02682'
down_revision: Union[str, Sequence[str], None] = '05cd2f2d7144'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_conversations_org_created', 'conversations', ['organization_id', 'created_at'], unique=False)
    op.create_index('ix_messages_conv_created', 'messages', ['conversation_id', 'created_at'], unique=False)
    op.create_index('ix_org_members_org_role', 'organization_members', ['organization_id', 'role'], unique=False)
    op.create_index('ix_tickets_org_priority', 'tickets', ['organization_id', 'priority'], unique=False)
    op.create_index('ix_tickets_org_status', 'tickets', ['organization_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tickets_org_status', table_name='tickets')
    op.drop_index('ix_tickets_org_priority', table_name='tickets')
    op.drop_index('ix_org_members_org_role', table_name='organization_members')
    op.drop_index('ix_messages_conv_created', table_name='messages')
    op.drop_index('ix_conversations_org_created', table_name='conversations')
    # ### end Alembic commands ###
