"""add_token_tracking

Revision ID: 5757ee4bff82
Revises: 24817b37bd1f
Create Date: 2026-08-21 17:07:31.753038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5757ee4bff82'
down_revision: Union[str, Sequence[str], None] = '24817b37bd1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_usage', sa.Column('prompt_tokens_used', sa.BigInteger(), nullable=False, server_default='0'))
    op.add_column('organization_usage', sa.Column('completion_tokens_used', sa.BigInteger(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization_usage', 'completion_tokens_used')
    op.drop_column('organization_usage', 'prompt_tokens_used')
    # ### end Alembic commands ###
