"""add ticket - notes

Revision ID: 7985f3f8a754
Revises: 45c4ab7611a9
Create Date: 2026-07-15 15:06:53.228119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7985f3f8a754'
down_revision: Union[str, Sequence[str], None] = '45c4ab7611a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_notes',
    sa.Column('ticket_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_notes_author_id'), 'ticket_notes', ['author_id'], unique=False)
    op.create_index(op.f('ix_ticket_notes_ticket_id'), 'ticket_notes', ['ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_notes_ticket_id'), table_name='ticket_notes')
    op.drop_index(op.f('ix_ticket_notes_author_id'), table_name='ticket_notes')
    op.drop_table('ticket_notes')
    # ### end Alembic commands ###
