"""remove extension from documents

Revision ID: c79fc72aa7c5
Revises: 5b78cb846e0c
Create Date: 2026-07-06 14:35:30.928321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c79fc72aa7c5'
down_revision: Union[str, Sequence[str], None] = '5b78cb846e0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'extension')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('extension', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
